export const T = {
  GET_PHOTOS: "GET_PHOTOS",
  GET_PHOTOS_SUCCESS: "GET_PHOTOS_SUCCESS",
  GET_PHOTOS_ERROR: "GET_PHOTOS_ERROR",
  GET_PHOTO: "GET_PHOTO",
  GET_PHOTO_SUCCESS: "GET_PHOTO_SUCCESS",
  GET_PHOTO_ERROR: "GET_PHOTO_ERROR"
}
